services:
  db:
    image: postgres:16-alpine
    ports:
      - "54329:5432"
    environment:
      POSTGRES_DB: sbory
      POSTGRES_USER: sbory
      POSTGRES_PASSWORD: sbory
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  pgdata_dev:
